FROM ruby:2.5

WORKDIR /rails_app

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        git \
        supervisor \
        libpq-dev \
        vim \
        && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV EDITOR vim

ADD ./Gemfile /rails_app/
ADD ./Gemfile.lock /rails_app/

RUN bundle config --global jobs `cat /proc/cpuinfo | grep processor | wc -l | xargs -I % expr % - 1`

ADD supervisord.conf /etc/supervisor/conf.d/zoo-events-stats-postgres.conf
ADD ./ /rails_app/

EXPOSE 80

CMD /rails_app/scripts/docker/start.sh
